services:
  mysql:
    container_name: mysql
    image: mysql:8.3
    env_file:
      - .env
    ports:
      - "3306:3306"
  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"
